# version: "3.9"

# services:
#   nedbank-server:
#     build: .
#     container_name: nedbank-server
#     ports:
#       - "5000:5000"
#     env_file:
#       - .env
#     depends_on:
#       - postgres-db
#     restart: always
#     environment:
#       DATABASE_URL: postgres://nedbank_user:password123@postgres-db:5432/nedbank_db
#       PORT: 5000
#       JWT_SECRET: myverysecretkey
#       REFRESH_SECRET: myrefreshsecret
#       EMAIL_USER: mkwapatirar@gmail.com
#       EMAIL_PASS: yfxb qprc gsue hutv
#       EMAIL_HOST: smtp.gmail.com
#       EMAIL_PORT: 587

#   postgres-db:
#     image: postgres:17-alpine
#     container_name: postgres-db
#     restart: always
#     environment:
#       POSTGRES_DB: nedbank_db
#       POSTGRES_USER: nedbank_user
#       POSTGRES_PASSWORD: password123
#     ports:
#       - "5433:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # âœ… fixed line

# volumes:
#   pgdata:
